/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaMessageQueues;

import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClientBuilder;
import com.amazonaws.services.sqs.model.AmazonSQSException;
import com.amazonaws.services.sqs.model.CreateQueueResult;
import com.amazonaws.services.sqs.model.SendMessageRequest;
import sun.rmi.runtime.Log;

import java.util.Timer;
import java.util.TimerTask;
import java.util.UUID;

public class Producer {
    public static UUID getUUID(){
        UUID uuid = UUID.randomUUID();
        return uuid;
    }

    public static void sendMessage() {
        AmazonSQS sqs = AmazonSQSClientBuilder.defaultClient();

        String QUEUE_NAMEA = "QueueA";
        String QUEUE_NAMEB = "QueueB";
        String QUEUE_NAMEC = "QueueC";

        String queueUrlA = sqs.getQueueUrl(QUEUE_NAMEA).getQueueUrl();
        String queueUrlB = sqs.getQueueUrl(QUEUE_NAMEB).getQueueUrl();
        String queueUrlC = sqs.getQueueUrl(QUEUE_NAMEC).getQueueUrl();

        SendMessageRequest send_msg_request = new SendMessageRequest()
                .withQueueUrl(queueUrlA)
                .withMessageBody("hello world - " + getUUID())
                .withDelaySeconds(5);
        sqs.sendMessage(send_msg_request);
    }

    public static void sendManyMessages() throws InterruptedException{
        // sleep

        while(true) {
            sendMessage();
            System.out.println("sending");
            Thread.sleep(500);
        }
    }

}
